---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-environment-secrets
  namespace: infra
spec:
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster-secrets-store
    kind: ClusterSecretStore
  target:
    name: atlantis-environment-secrets
    template:
      data:
        GITHUB_USER_SSH_KEY: >-
          {{ printf "{{ .github_ssh | toString }}" }}
        GIT_SSH_COMMAND: >-
          {{ printf "{{ .github_ssh_command | toString }}" }}
  data:
    - secretKey: github_ssh
      remoteRef:
        key: atlantis-credentials
        property: github-ssh-access-private-key
    - secretKey: github_ssh_command
      remoteRef:
        key: atlantis-credentials
        property: github-ssh-command